projects:
  digitaltwin:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/graphql/types.ts # https://github.com/aws-amplify/amplify-codegen/issues/734
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/types.ts
        docsFilePath: src/graphql
        maxDepth: 5
extensions:
  amplify:
    version: 3
