/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FraiaAPIModels = Agent | Conversation | ConversMessage;
export type VoiceMode = "WHISPER" | "ELEVEN_LABS" | "HEYGEN";

export interface Agent {
  _id: string;
  name: string;
  type: string;
  orchestrator_agent_id?: string | null;
  knowledge_base_id?: string | null;
  description: string;
  is_active?: boolean | null;
  allow_routing?: boolean | null;
  config: AgentConfig;
  query_strategy?: QueryStrategy | null;
  avatar_config?: AvatarConfig | null;
}
export interface AgentConfig {
  prompt_template: string;
  pdc?: string | null;
  tools?: Tools[] | null;
}
export interface Tools {
  name: string;
  type: string;
  description: string;
  processing_message?: string | null;
  is_active?: boolean | null;
  config: ToolConfigs;
  llm_schema: string;
}
export interface ToolConfigs {
  endpoint: string;
  method: string;
  fixed_query_parameters?: {
    [k: string]: unknown;
  } | null;
  query_params: string[] | null;
  fixed_body_parameters?: {
    [k: string]: unknown;
  } | null;
  body: string[] | null;
  headers: {
    [k: string]: unknown;
  } | null;
}
export interface QueryStrategy {
  temperature?: number | null;
  model?: string | null;
  max_tokens?: number | null;
}
export interface AvatarConfig {
  avatar?: string | null;
  voice_mode?: VoiceMode | null;
  voice_id?: string | null;
  display_name?: string | null;
}
export interface Conversation {
  _id: string;
  /**
   * Agent ID
   */
  agent_id: string;
  /**
   * User ID
   */
  user_id: string;
  start_time?: string | null;
  end_time?: string | null;
  current_worker_agent?: string | null;
}
export interface ConversMessage {
  _id: string;
  conversation_id: string;
  sender: string;
  sender_id: string;
  content: string;
  sent_at: string;
  type: string;
}
